const toblame = normal: [
            "Juan Bernat",
            "Kriminelle Ausländer",
            "Die da oben",
            "Dämlicher Flanders",
            "Globalisten",
            "Die Grühüünen",
            "Altparteien",
            "Windräder",
            "Deep State",
            "Faule Beamte",
            "Faule Ausländer",
            "Jugend von heute",
            "Gen Z",
            "Schlafschafe",
            "Die Linken",
            "Sogenannte Experten",
            "Klimalügner",
            "Klimakleber",
            "Weltjudentum",
            "Eliten",
            "Die Studierten",
            "korrupte Politiker",
            "Mein verfickter Nachbar",
            "Kleine Paschas",
            "Asylanten",
            "Gutmenschen",
            "Reptiloiden",
            "Big Pharma",
            "Influencer",
            "Feministen",
            "Technokraten",
            "Vegane Hipster",
            "Künstliche Intelligenz",
            "Die EU",
            "Brüssel",
            "Gender-Gaga",
            "Cancel Culture",
            "ÖRR (öffentlich-rechtlicher Rundfunk)",
            "Lügenpresse",
            "Steuerberater",
            "Mietwucherer",
            "Kapitalismus",
            "Sozialismus",
            "Kommunisten",
            "Gendersprache",
            "Schulreform",
            "Volksverräter",
            "Maskenpflicht",
            "Digitalisierung",
            "TikTok",
            "Facebook-Algorithmen",
            "Die Chinesen",
            "Die Amerikaner",
            "Hacker",
            "Lobbyisten",
            "Propagandamedien",
            "Der tiefe Staat",
            "Das Finanzamt",
            "Der Chef",
            "Scheidungsanwälte",
            "Influencer",
            "Kryptobros",
            "NFTs",
            "Die Rentner",
            "Kreditkartenfirmen",
            "Weltwirtschaftsforum",
            "George Soros",
            "Elon Musk",
            "Jeff Bezos",
            "Bill Gates",
            "Greta Thunberg",
            "Mark Zuckerberg",
            "Autofahrer",
            "Radfahrer",
            "E-Scooter-Fahrer",
            "Pendler",
            "Verkehrspolitik",
            "SUV-Fahrer",
            "Die neue Rechtschreibung",
            "Montessorischulen",
            "Influencer-Eltern",
            "Kinderschutzbund",
            "Die Bahn",
            "DAX-Unternehmen",
            "Anzugträger",
            "Digitalnomaden",
            "Dropshipper",
            "Berater",
            "Raucher",
            "Nichtraucher",
            "Verschwörungstheoretiker",
            "Esoteriker",
            "Linkstwitter",
            "Rechtstwitter",
            "Die Mitte",
            "Der Kapitalmarkt",
            "Die Gewerkschaften",
            "Kitas",
            "Fridays for Future",
            "Extinction Rebellion",
            "Die WHO",
            "Die UNO",
            "Regenbogenflaggen",
            "Die CSU",
            "Die FDP",
            "Die SPD",
            "CDU-Merkelismus",
            "Querdenker",
            "Impfgegner",
            "Impfpflicht",
            "Banken",
            "Kreditvergabe",
            "Bauämter",
            "Bauauflagen",
            "Die Immobilienblase",
            "Zugezogene",
            "Dorfbewohner",
            "Touristen",
            "Gentrifizierer",
            "Mietnomaden",
            "Steuerschlupflöcher",
            "Offshore-Konten",
            "Schweizer Banken",
            "Die FIFA",
            "Die UEFA",
            "Die Schiris",
            "Kneipenkicker",
            "Kryptowährungen",
            "Altcoins",
            "Dogecoin",
            "Daytrader",
            "Wallstreetbets",
            "Der Euro",
            "Der Dollar",
            "Die AfD",
            "Antifa",
            "Nazis",
            "Pazifisten",
            "Funktionäre",
            "Versicherungsmakler",
            "Immobilienhaie",
            "Versicherungen",
            "Kreditkartenanbieter",
            "Telekomhotlines",
            "Callcenter-Mitarbeiter",
            "Paketboten",
            "Amazon-Bewertungen",
            "Online-Bewertungen",
            "Apple-User",
            "Android-User",
            "Die Cloud",
            "Passwortmanager",
            "Cookies",
            "Google-Ads",
            "Pop-Up-Werbung",
            "Influencer-Werbung",
            "Coaches",
            "Life Coaches",
            "Fitness Coaches",
            "Online-Dating",
            "Tinder",
            "OnlyFans",
            "Boomer",
            "Millennials",
            "iPhone-Besitzer",
            "Android-Besitzer",
            "Gaming-Streamer",
            "Politiker-Talkshows",
            "Steuerberater",
            "Zensurbehörden",
            "Algorithmen",
            "Autokorrektur",
            "Captcha-Codes",
            "NFT-Pusher",
            "Das Metaverse",
            "Chatbots",
            "ChatGPT",
            "Der Mond",
            "Meine eigene Faulheit",
            "Die IT",
            "Karl Klammer",
            "Meine eigene Faulheit",
            "Toby Flenderson",
            "Jim Harper",
            "Der Ernie",
            "Der Ulf",
            "Meine eigene Faulheit",
            "Der USB-Treiber",
            "Der Drucker",
            "BMW-Fahrer",
            "Mercedes-Fahrer",
            "Sonntagsfahrer",
            "Raser",
            "Startup-Bros"
        ],
        radical: ["MegaBob", "SuperAlice", "UltraEve", "RadCharlie", "HyperDave"],
        "radical-as-fk": ["Bobinator", "Alicezilla", "Evex", "Charlieon", "Davemaster"],
        conspiracy: ["Deep Bob", "Illuminati Alice", "Eve the Shadow", "Charlie Q", "Dave the Lizard"]
};
        const slotItemsContainer = document.getElementById('slotItems');
        const lever = document.getElementById('lever');
        const modeSelector = document.getElementById('modeSelector');
        const resultDisplay = document.getElementById('result');

        let spinning;

        function startSpin(names) {
            slotItemsContainer.style.animation = 'none';
            slotItemsContainer.innerHTML = names.map(name => `<div class="slot-item">${name}</div>`).join('');

            setTimeout(() => {
                slotItemsContainer.style.animation = `spin 0.1s linear infinite`;
            }, 10);
        }

        function stopSpin(names) {
            clearInterval(spinning);
            const finalName = names[Math.floor(Math.random() * names.length)];
            slotItemsContainer.style.animation = 'none';
            slotItemsContainer.innerHTML = `<div class="slot-item">${finalName}</div>`;
            resultDisplay.textContent = `The machine stopped on: ${finalName}`;
        }

        lever.addEventListener('click', () => {
            // Animate the lever
            lever.style.transform = 'rotate(20deg)';
            setTimeout(() => {
                lever.style.transform = 'rotate(0deg)';
            }, 200);

            // Start spinning
            const mode = modeSelector.value;
            const names = namePools[mode];
            startSpin(names);

            // Stop spinning after 3 seconds
            setTimeout(() => {
                stopSpin(names);
            }, 3000);
        });
