const namePools = {
            radical: [
            "Ausländer",
            "Windräder",
            "Deep State",
            "Altparteien",
            "Sozialtourismus",
            "Klimakleber",
            "Kleine Paschas",
            "Asylanten",
            "Gender-Gaga",
            "Cancel Culture",
            "Volksverräter",
            "Maskenpflicht",
            ],
            conspiracy:[
            "Globalisten",
            "Schlafschafe",
            "Klimalügner",
            "Weltjudentum",
            "Gutmenschen",
            "Reptiloiden",
            "Big Pharma",
            "ÖRR (öffentlich-rechtlicher Rundfunk)",
            "Lügenpresse",
            ],
            normal: [
            "Juan Bernat",
            "Die da oben",
            "Dämlicher Flanders",
            "Die Grühünen",
            "Faule Beamte",
            "Jugend von heute",
            "Gen Z",
            "Die Linken",
            "Sogenannte Experten",
            "Eliten",
            "Die Studierten",
            "korrupte Politiker",
            "Mein verfickter Nachbar",
            "Influencer",
            "Feministen",
            "Technokraten",
            "Vegane Hipster",
            "Künstliche Intelligenz",
            "Die EU",
            "Brüssel",
            "Steuerberater",
            "Mietwucherer",
            "Kapitalismus",
            "Sozialismus",
            "Kommunisten",
            "Gendersprache",
            "Schulreform",
            "Digitalisierung",
            "TikTok",
            "Facebook-Algorithmen",
            "Die Chinesen",
            "Die Amerikaner",
            "Hacker",
            "Lobbyisten",
            "Propagandamedien",
            "Der tiefe Staat",
            "Das Finanzamt",
            "Der Chef",
            "Scheidungsanwälte",
            "Influencer",
            "Kryptobros",
            "NFTs",
            "Die Rentner",
            "Kreditkartenfirmen",
            "Weltwirtschaftsforum",
            "George Soros",
            "Elon Musk",
            "Jeff Bezos",
            "Bill Gates",
            "Greta Thunberg",
            "Mark Zuckerberg",
            "Autofahrer",
            "Radfahrer",
            "E-Scooter-Fahrer",
            "Pendler",
            "Verkehrspolitik",
            "SUV-Fahrer",
            "Die neue Rechtschreibung",
            "Montessorischulen",
            "Influencer-Eltern",
            "Kinderschutzbund",
            "Die Bahn",
            "DAX-Unternehmen",
            "Anzugträger",
            "Digitalnomaden",
            "Dropshipper",
            "Berater",
            "Raucher",
            "Nichtraucher",
            "Verschwörungstheoretiker",
            "Esoteriker",
            "Linkstwitter",
            "Rechtstwitter",
            "Die Mitte",
            "Der Kapitalmarkt",
            "Die Gewerkschaften",
            "Kitas",
            "Fridays for Future",
            "Extinction Rebellion",
            "Die WHO",
            "Die UNO",
            "Regenbogenflaggen",
            "Die CSU",
            "Die FDP",
            "Die SPD",
            "CDU-Merkelismus",
            "Querdenker",
            "Impfgegner",
            "Impfpflicht",
            "Banken",
            "Kreditvergabe",
            "Bauämter",
            "Bauauflagen",
            "Die Immobilienblase",
            "Zugezogene",
            "Dorfbewohner",
            "Touristen",
            "Gentrifizierer",
            "Mietnomaden",
            "Steuerschlupflöcher",
            "Offshore-Konten",
            "Schweizer Banken",
            "Die FIFA",
            "Die UEFA",
            "Die Schiris",
            "Kneipenkicker",
            "Kryptowährungen",
            "Altcoins",
            "Dogecoin",
            "Daytrader",
            "Wallstreetbets",
            "Der Euro",
            "Der Dollar",
            "Die AfD",
            "Antifa",
            "Nazis",
            "Pazifisten",
            "Funktionäre",
            "Versicherungsmakler",
            "Immobilienhaie",
            "Versicherungen",
            "Kreditkartenanbieter",
            "Telekomhotlines",
            "Callcenter-Mitarbeiter",
            "Paketboten",
            "Amazon-Bewertungen",
            "Online-Bewertungen",
            "Apple-User",
            "Android-User",
            "Die Cloud",
            "Passwortmanager",
            "Cookies",
            "Google-Ads",
            "Pop-Up-Werbung",
            "Influencer-Werbung",
            "Coaches",
            "Life Coaches",
            "Fitness Coaches",
            "Online-Dating",
            "Tinder",
            "OnlyFans",
            "Boomer",
            "Millennials",
            "iPhone-Besitzer",
            "Android-Besitzer",
            "Gaming-Streamer",
            "Politiker-Talkshows",
            "Steuerberater",
            "Zensurbehörden",
            "Algorithmen",
            "Autokorrektur",
            "Captcha-Codes",
            "NFT-Pusher",
            "Das Metaverse",
            "Chatbots",
            "ChatGPT",
            "Der Mond",
            "Meine eigene Faulheit",
            "Die IT",
            "Karl Klammer",
            "Meine eigene Faulheit",
            "Toby Flenderson",
            "Jim Harper",
            "Der Ernie",
            "Der Ulf",
            "Meine eigene Faulheit",
            "Der USB-Treiber",
            "Der Drucker",
            "BMW-Fahrer",
            "Mercedes-Fahrer",
            "Sonntagsfahrer",
            "Raser",
            "Startup-Bros"],
};