const namePools = {
            radical: [
            "Ausländer",
            "Windräder",
            "Deep State",
            "Altparteien",
            "Sozialtourismus",
            "Klimakleber",
            "Kleine Paschas",
            "Asylanten",
            "Gender-Gaga",
            "Cancel Culture",
            "Maskenpflicht",

            ],
            conspiracy:[
            "Volksverräter",
            "Propagandamedien",
            "Deep State",
            "Zensurbehörden",
            "Globalisten",
            "Schlafschafe",
            "Klimalügner",
            "Weltjudentum",
            "Gutmenschen",
            "Reptiloiden",
            "Big Pharma",
            "ÖRR (öffentlich-rechtlicher Rundfunk)",
            "Lügenpresse",
            ],
            nerdy: [
            "Karl Klammer",
            "Toby!!!",
            "Der Ernie",
            "Der Ulf",
            "Dämlicher Flanders",
            "42",
            "Klingonen",
            "Bender"
            ],
            normal: [
            "Juan Bernat",
            "Die da oben",
            "Die Grühünen",
            "Faule Beamte",
            "Jugend von heute",
            "Gen Z",
            "Die Linken",
            "Sogenannte Experten",
            "Eliten",
            "Die Studierten",
            "korrupte Politiker",
            "Mein verfickter Nachbar",
            "Influencer",
            "Feministen",
            "Technokraten",
            "Vegane Hipster",
            "Künstliche Intelligenz",
            "Die EU",
            "Brüssel",
            "Steuerberater",
            "Mietwucherer",
            "Kapitalismus",
            "Sozialismus",
            "Kommunisten",
            "Gendersprache",
            "Schulreform",
            "Digitalisierung",
            "TikTok",
            "Soziale Medien",
            "Die Chinesen",
            "Die Amerikaner",
            "Hacker",
            "Lobbyisten",
            "Das Finanzamt",
            "Der Chef",
            "Kryptobros",
            "Rentner",
            "Weltwirtschaftsforum",
            "George Soros",
            "Elon Musk",
            "Jeff Bezos",
            "Bill Gates",
            "Greta Thunberg",
            "Mark Zuckerberg",
            "Autofahrer",
            "Radfahrer",
            "E-Scooter-Fahrer",
            "Pendler",
            "Verkehrspolitik",
            "SUV-Fahrer",
            "Die neue Rechtschreibung",
            "Die Bahn",
            "Konzerne",
            "Anzugträger",
            "Berater",
            "Raucher",
            "Nichtraucher",
            "Verschwörungstheoretiker",
            "Esoteriker",
            "Der Kapitalmarkt",
            "Die Gewerkschaften",
            "Kitas",
            "Fridays for Future",
            "Extinction Rebellion",
            "Die WHO",
            "Die UNO",
            "Regenbogenflaggen",
            "Die CSU",
            "Die FDP",
            "Die SPD",
            "CDU-Merkelismus",
            "Querdenker",
            "Impfgegner",
            "Impfpflicht",
            "Bürokraten",
            "Bauauflagen",
            "Die Immobilienblase",
            "Zugezogene",
            "Touristen",
            "Mietnomaden",
            "Steuerschlupflöcher",
            "Banken",
            "Die FIFA",
            "Die UEFA",
            "Der Schiri",
            "Kneipenkicker",
            "Kryptowährungen",
            "Finanzheinis",
            "Der Euro",
            "Der Dollar",
            "Die AfD",
            "Antifa",
            "Nazis",
            "Pazifisten",
            "Funktionäre",
            "Drückerkolonnen",
            "Banker",
            "Versicherungen",
            "Telekomhotlines",
            "Online-Handel",
            "Die Cloud",
            "Influence",
            "Coaches",
            "Life Coaches",
            "Fitness Coaches",
            "Online-Dating",
            "Tinder",
            "OnlyFans",
            "Boomer",
            "Millennials",
            "iPhone-Besitzer",
            "Android-Besitzer",
            "Talkshows",
            "Steuerberater",
            "Autokorrektur",
            "Captcha-Codes",
            "Das Metaverse",
            "Chatbots",
            "ChatGPT",
            "Der Mond",
            "Die IT",
            "Meine eigene Faulheit",
            "USB-Treiber",
            "BMW-Fahrer",
            "Mercedes-Fahrer",
            "Sonntagsfahrer",
            "Raser",
            "Tempolimit",
            "Startup-Bros"],
};

namePools.general = [
    ...namePools.radical,
    ...namePools.conspiracy,
    ...namePools.nerdy,
    ...namePools.normal
];