const namePools = {
            radical: [
            "Bürgergeldempfänger",
            "Sozialschmarotzer",
            "Ausländer",
            "Windräder",
            "Altparteien",
            "Sozialtourismus",
            "Klimakleber",
            "Kleine Paschas",
            "Asylanten",
            "Gender-Gaga",
            "Cancel Culture",
            "Maskenpflicht",
            "Wokeness",
            "Regenbogenflaggen",
            "Sprachpolizei",
            "Greta Thunberg",
            ],
            conspiracy:[
            "Volksverräter",
            "Propagandamedien",
            "Deep State",
            "Zensurbehörden",
            "Schlafschafe",
            "Mark Zuckerberg",
            "rotlakierte Nazis",
            "Klimalügner",
            "Weltwirtschaftsforum",
            "Gutmenschen",
            "Reptiloiden",
            "Big Pharma",
            "ÖRR (öffentlich-rechtlicher Rundfunk)",
            "Lügenpresse",
            "Eliten",
            "Bill Gates",
            "Die WHO",
            "Die UNO",
            "Big Tech",
            "Big Oil"
            ],
            nerdy: [
            "Karl Klammer",
            "Toby!!!",
            "Der Ernie",
            "Der Ulf",
            "Dämlicher Flanders",
            "42",
            "Klingonen",
            "Bender",
            "Die unbekannte Linke"
            ],
            normal: [
            "Juan Bernat",
            "Die da oben",
            "Die Grünen",
            "Faule Beamte",
            "Jugend von heute",
            "Gen Z",
            "Sogenannte Experten",
            "Die Studierten",
            "korrupte Politiker",
            "Mein verfickter Nachbar",
            "Influencer",
            "Feministen",
            "Vegane Hipster",
            "Künstliche Intelligenz",
            "Brüssel",
            "Steuerberater",
            "Mietwucherer",
            "Heuschrecken",
            "Kapitalismus",
            "Sozialismus",
            "Kommunisten",
            "Ampel",
            "Schulreform",
            "Digitalisierung",
            "TikTok",
            "Soziale Medien",
            "Die Chinesen",
            "Die Amerikaner",
            "Hacker",
            "Lobbyisten",
            "Finanzämter",
            "Mein idiotischer Chef",
            "Rentner",
            "Autofahrer",
            "Radfahrer",
            "E-Scooter",
            "SUV-Fahrer",
            "Die neue Rechtschreibung",
            "Die Bahn",
            "Konzerne",
            "Anzugträger",
            "Berater",
            "Raucher",
            "Nichtraucher",
            "Verschwörungstheoretiker",
            "Esoteriker",
            "Kapitalmarkt",
            "Gewerkschaften",
            "Fridays for Future",
            "Letzte Generation",
            "Querdenker",
            "Impfgegner",
            "Impfpflicht",
            "Bürokraten",
            "Bauvorschriften",
            "Spekulanten",
            "Zugezogene",
            "Touristen",
            "Mietnomaden",
            "Steuerschlupflöcher",
            "Banken",
            "Die FIFA",
            "Die UEFA",
            "Der Schiri",
            "Bitcoin",
            "Der Euro",
            "Der Dollar",
            "Pazifisten",
            "Funktionäre",
            "Drückerkolonnen",
            "Banker",
            "Versicherungen",
            "Callcenter",
            "Online-Handel",
            "Die Cloud",
            "Fitness Coaches",
            "Online-Dating",
            "Tinder",
            "OnlyFans",
            "Boomer",
            "Millennials",
            "Smartphones",
            "Talkshows",
            "Steuerberater",
            "Autokorrektur",
            "ChatGPT",
            "Der Mond",
            "Die IT",
            "Meine eigene Faulheit",
            "Tempolimit"
            ],
};

namePools.general = [
    ...namePools.radical,
    ...namePools.conspiracy,
    ...namePools.nerdy,
    ...namePools.normal
];